### PR TITLE
restore action handling to WC status, use data store to delete actions

### LINKED ISSUE #485: Run action link does not work in WC status page
This is a regression caused by https://github.com/woocommerce/action-scheduler/commit/e10a7db232c358935b3ebc0a51e379eb839b6d17 which moved the action processing to the Tools -> Scheduled Actions page hook. That page hook isn't fired when the Scheduled Action screen is loaded under WooCommerce -> Status.

Originally reported in https://github.com/woocommerce/woocommerce/issues/25870

### PR DESCRIPTION
**Pull request by rrennick**
Closes #485 

This PR restores the action handling to the Scheduled Actions screen under WooCommerce -> Status -> Scheduled Actions. The handling was removed in #354. 

While investigating this I noticed that the bulk delete action attempts to delete the actions from the default data store. The PR updates that function to use the data store to delete the actions.

### Testing

1. In master confirm that neither the bulk delete action or the action links work in the WC status page
1. Switch to this branch
1. Update `action-scheduler.php` to artificially bump the version
```
-if ( ! function_exists( 'action_scheduler_register_3_dot_1_dot_2' ) ) {
+if ( ! function_exists( 'action_scheduler_register_3_dot_1_dot_3' ) ) {
 
        if ( ! class_exists( 'ActionScheduler_Versions' ) ) {
                require_once( 'classes/ActionScheduler_Versions.php' );
                add_action( 'plugins_loaded', array( 'ActionScheduler_Versions', 'initialize_latest_version' ), 1, 0 );
        }
 
-       add_action( 'plugins_loaded', 'action_scheduler_register_3_dot_1_dot_2', 0, 0 );
+       add_action( 'plugins_loaded', 'action_scheduler_register_3_dot_1_dot_3', 0, 0 );
 
-       function action_scheduler_register_3_dot_1_dot_2() {
+       function action_scheduler_register_3_dot_1_dot_3() {
                $versions = ActionScheduler_Versions::instance();
-               $versions->register( '3.1.2', 'action_scheduler_initialize_3_dot_1_dot_2' );
+               $versions->register( '3.1.3', 'action_scheduler_initialize_3_dot_1_dot_3' );
        }
 
-       function action_scheduler_initialize_3_dot_1_dot_2() {
+       function action_scheduler_register_3_dot_1_dot_3() {
                $versions = ActionScheduler_Versions::instance();
-               $versions->register( '3.1.2', 'action_scheduler_initialize_3_dot_1_dot_2' );
+               $versions->register( '3.1.3', 'action_scheduler_initialize_3_dot_1_dot_3' );
        }
 
-       function action_scheduler_initialize_3_dot_1_dot_2() {
+       function action_scheduler_initialize_3_dot_1_dot_3() {
                require_once( 'classes/abstracts/ActionScheduler.php' );
                ActionScheduler::init( __FILE__ );
        }
 
        // Support usage in themes - load this version if no plugin has loaded a version yet.
        if ( did_action( 'plugins_loaded' ) && ! class_exists( 'ActionScheduler' ) ) {
-               action_scheduler_initialize_3_dot_1_dot_2();
+               action_scheduler_initialize_3_dot_1_dot_3();
                do_action( 'action_scheduler_pre_theme_init' );
                ActionScheduler_Versions::initialize_latest_version();
        }
```
1. Check the WC status report to verify the bumped version is active
1. Test action links and bulk actions in both the `Tools` and `WooCommerce -> Status` Scheduled Actions screens work.

### CODE REVIEW

File: classes/ActionScheduler_AdminView.php [hunk 1]
```diff
@@ -91,6 +91,7 @@ public function process_admin_ui() {
 	 */
 	public function render_admin_ui() {
 		$table = new ActionScheduler_ListTable( ActionScheduler::store(), ActionScheduler::logger(), ActionScheduler::runner() );
+		$table->process_actions();
```
Comment (jeffstieler) [inline classes/ActionScheduler_AdminView.php]: Should the call to `process_actions()` be removed from `process_admin_ui()`? It looks like this will fire twice when going to Tools > Scheduled Actions.

Comment (rrennick) [reply classes/ActionScheduler_AdminView.php]: @jeffstieler Thanks for the suggestion. The PR has been updated.

**Comment by jeffstieler** [comment]
Testing now @rrennick - please update the version in `package.json` as well.

**Comment by thenbrent** [comment]
> The PR updates that function to use the data store to delete the actions.

That's likely related to #484.

**Comment by rrennick** [comment]
> The PR updates

@thenbrent That was a typo `The` should have been `This`. It's the small change in the abstract list table.

> If the version bump was meant to happen in this PR

@jeffstieler Thanks for catching that.
